# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1At07eFtuYcq4ZVn4hQQZLP8yrFywdutA
"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, precision_score, recall_score
# Import Ensemble and Base Models
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import warnings

warnings.filterwarnings('ignore')


# 1. Data Loading & K-Means Clustering

df = pd.read_csv("hotel_bookings_preprocessed.csv")

print("Step 1: Running K-Means Clustering based on customer behaviors...")
cluster_cols = ['adr', 'stays_in_weekend_nights', 'stays_in_week_nights', 'total_of_special_requests']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[cluster_cols])

kmeans = KMeans(n_clusters=3, random_state=42)
df['customer_cluster'] = kmeans.fit_predict(X_scaled)
print(" -> [SUCCESS] Customer data has been segmented into 3 clusters (0, 1, 2).")
print("-" * 65)


# 2. Base & Ensemble Model Definitions

# Define base estimators for Soft Voting
base_models = [
    ('lr', LogisticRegression(max_iter=1000, random_state=42)),
    ('dt', DecisionTreeClassifier(max_depth=6, random_state=42))
]

models = {
    # 1. Bagging Framework: Random Forest
    'Random Forest (Bagging)': RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42),

    # 2. Voting Framework: Soft Voting Ensemble
    'Soft Voting (Ensemble)': VotingClassifier(estimators=base_models, voting='soft')
}


# 3. Cluster-wise 5-Fold Cross Validation

folds = 5
skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=42)

print("Step 2: Executing 5-Fold Cross Validation via Baseline Ensembles\n")

for cluster_id in sorted(df['customer_cluster'].unique()):
    df_cluster = df[df['customer_cluster'] == cluster_id]

    total_samples = len(df_cluster)
    base_cancel_rate = df_cluster['is_canceled'].mean() * 100


    print(f" [Customer Cluster {cluster_id}] Total Samples: {total_samples} | Base Cancellation Rate: {base_cancel_rate:.2f}%")


    X_c = df_cluster.drop(columns=['is_canceled', 'customer_cluster']).reset_index(drop=True)
    y_c = df_cluster['is_canceled'].reset_index(drop=True)

    for model_name, model in models.items():
        print(f"  [{model_name}] Running 5-Fold CV")

        f1_folds, prec_folds, rec_folds = [], [], []

        for train_idx, val_idx in skf.split(X_c, y_c):
            X_train, X_val = X_c.iloc[train_idx], X_c.iloc[val_idx]
            y_train, y_val = y_c.iloc[train_idx], y_c.iloc[val_idx]

            model.fit(X_train, y_train)
            y_pred = model.predict(X_val)

            f1_folds.append(f1_score(y_val, y_pred) * 100)
            prec_folds.append(precision_score(y_val, y_pred) * 100)
            rec_folds.append(recall_score(y_val, y_pred) * 100)

        avg_f1 = np.mean(f1_folds)
        avg_prec = np.mean(prec_folds)
        avg_rec = np.mean(rec_folds)

        print(f"   -> [Final Mean] F1-Score: {avg_f1:.2f}% | Precision: {avg_prec:.2f}% | Recall: {avg_rec:.2f}%")
    print("-" * 65)

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score, precision_score, recall_score
# Import Classifiers Specified in the PDF Slides
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
import warnings

warnings.filterwarnings('ignore')


# 1. Data Loading & K-Means Clustering (Stage 1)

df = pd.read_csv("hotel_bookings_preprocessed.csv")

print("Step 1: Segmenting customer base via K-Means Clustering...")
cluster_cols = ['adr', 'stays_in_weekend_nights', 'stays_in_week_nights', 'total_of_special_requests']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[cluster_cols])

kmeans = KMeans(n_clusters=3, random_state=42)
df['customer_cluster'] = kmeans.fit_predict(X_scaled)
print(" -> [SUCCESS] Customer segments established into 3 behavior groups.")
print("-" * 75)


# 2. Boosting Model Configurations (Based on Lecture Specifications)

models = {
    # [Model 1] AdaBoost: Uses Decision Stumps (max_depth=1) as base estimators (Ref: Slide Page 61, 72)
    'AdaBoost (Stumps)': AdaBoostClassifier(
        estimator=DecisionTreeClassifier(max_depth=1, random_state=42),
        n_estimators=100,
        random_state=42
    ),

    # [Model 2] Gradient Boosting: Sequential optimization via gradient descent (Ref: Slide Page 113, 114)
    'Gradient Boosting': GradientBoostingClassifier(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=3,  # Slide Default Value
        random_state=42
    ),

    # [Model 3] XGBoost: Optimized eXtreme Gradient Boosting framework (Ref: Slide Page 116, 117)
    'XGBoost (Regularized)': XGBClassifier(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=3,
        random_state=42,
        eval_metric='logloss'
    )
}


# 3. Cluster-wise 5-Fold Cross Validation Loop (Stage 2)

folds = 5
skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=42)

print("Step 2: Training Boosting Ensembles under Stratified 5-Fold CV Framework\n")

for cluster_id in sorted(df['customer_cluster'].unique()):
    df_cluster = df[df['customer_cluster'] == cluster_id]

    total_samples = len(df_cluster)
    base_cancel_rate = df_cluster['is_canceled'].mean() * 100


    print(f" Customer Cluster {cluster_id} Samples: {total_samples} | Base Cancellation Rate: {base_cancel_rate:.2f}%")


    # Filter target and features
    X_c = df_cluster.drop(columns=['is_canceled', 'customer_cluster']).reset_index(drop=True)
    y_c = df_cluster['is_canceled'].reset_index(drop=True)

    # Evaluate 3 Boosting Frameworks sequentially
    for model_name, model in models.items():
        print(f"  [{model_name}] Processing 5-Fold Cross Validation...")

        f1_folds, prec_folds, rec_folds = [], [], []

        for train_idx, val_idx in skf.split(X_c, y_c):
            X_train, X_val = X_c.iloc[train_idx], X_c.iloc[val_idx]
            y_train, y_val = y_c.iloc[train_idx], y_c.iloc[val_idx]

            model.fit(X_train, y_train)
            y_pred = model.predict(X_val)

            # Store scores in percentage
            f1_folds.append(f1_score(y_val, y_pred) * 100)
            prec_folds.append(precision_score(y_val, y_pred) * 100)
            rec_folds.append(recall_score(y_val, y_pred) * 100)

        # Compute final validation averages
        avg_f1 = np.mean(f1_folds)
        avg_prec = np.mean(prec_folds)
        avg_rec = np.mean(rec_folds)

        print(f"   -> [Ensemble Mean] F1: {avg_f1:.2f}% | Precision: {avg_prec:.2f}% | Recall: {avg_rec:.2f}%")
    print("-" * 75)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import warnings

warnings.filterwarnings('ignore')



sns.set_theme(style="whitegrid")
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['axes.unicode_minus'] = False


# 2. 데이터 로드 및 K-Means 클러스터링

df = pd.read_csv("hotel_bookings_preprocessed.csv")

cluster_cols = ['adr', 'stays_in_weekend_nights', 'stays_in_week_nights', 'total_of_special_requests']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[cluster_cols])

kmeans = KMeans(n_clusters=3, random_state=42)
df['customer_cluster'] = kmeans.fit_predict(X_scaled)


# 3. 3개 군집용 3행 2열(총 6개) 대형 시본 도표 틀 생성

fig, axes = plt.subplots(3, 2, figsize=(15, 14))
fig.suptitle('5-Fold CV Feature Importance: Pure Bagging vs Random Forest', fontsize=20, fontweight='bold', y=0.98)

# PPT 스토리텔링용 군집 매핑 이름
cluster_names = {
    0: "Cluster 0: Budget Personal Travelers",
    1: "Cluster 1: Long-stay Family/Groups",
    2: "Cluster 2: High-spending VIPs"
}

folds = 5
skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=42)


# 4. 5-Fold 교차 검증 기반 중요도 추출 및 Seaborn 매핑

for row_idx, cluster_id in enumerate(sorted(df['customer_cluster'].unique())):
    df_cluster = df[df['customer_cluster'] == cluster_id]

    X_c = df_cluster.drop(columns=['is_canceled', 'customer_cluster']).reset_index(drop=True)
    y_c = df_cluster['is_canceled'].reset_index(drop=True)
    features = X_c.columns

    bagging_folds_imp = []
    rf_folds_imp = []

    # 5-Fold 루프 안에서 각 시험 라운드의 피처 중요도를 누적
    for train_idx, _ in skf.split(X_c, y_c):
        X_train, y_train = X_c.iloc[train_idx], y_c.iloc[train_idx]

        # 수업 PDF 규격 모델 설정 (Ref: Slide Page 26, 42, 43)
        m_bagging = BaggingClassifier(
            estimator=DecisionTreeClassifier(max_depth=7, random_state=42),
            n_estimators=100, random_state=42, n_jobs=-1
        )
        m_rf = RandomForestClassifier(n_estimators=100, max_depth=7, random_state=42)

        m_bagging.fit(X_train, y_train)
        m_rf.fit(X_train, y_train)

        # 중요도 저장 (Bagging은 100개 트리의 피처 중요도 평균 산출)
        bagging_fi = np.mean([tree.feature_importances_ for tree in m_bagging.estimators_], axis=0)
        bagging_folds_imp.append(bagging_fi)
        rf_folds_imp.append(m_rf.feature_importances_)

    # 5회 교차 검증의 최종 평균 스코어 계산
    bagging_final_avg = np.mean(bagging_folds_imp, axis=0)
    rf_final_avg = np.mean(rf_folds_imp, axis=0)

    # --- 시각화를 위한 Seaborn 데이터프레임 변환 파트 ---
    # 왼쪽 열: Pure Bagging Top 5
    df_bagging = pd.DataFrame({'Feature': features, 'Importance': bagging_final_avg}).sort_values(by='Importance', ascending=False).head(5)
    ax_left = axes[row_idx, 0]
    sns.barplot(x='Importance', y='Feature', data=df_bagging, ax=ax_left, palette="Blues_r")

    # 오른쪽 열: Random Forest Top 5
    df_rf = pd.DataFrame({'Feature': features, 'Importance': rf_final_avg}).sort_values(by='Importance', ascending=False).head(5)
    ax_right = axes[row_idx, 1]
    sns.barplot(x='Importance', y='Feature', data=df_rf, ax=ax_right, palette="Oranges_r")

    # --- 도표 세부 디자인 및 축 레이벨링 규칙 설정 ---
    if row_idx == 0:
        ax_left.set_title('Pure Bagging (Decision Trees)', fontsize=13, fontweight='bold', pad=10)
        ax_right.set_title(' Random Forest (Feature Subsets)', fontsize=13, fontweight='bold', pad=10)

    # 각 군집 행의 대표 이름을 Y축 바깥에 배치
    ax_left.set_ylabel(f"{cluster_names[cluster_id]}", fontsize=12, fontweight='bold', labelpad=15)
    ax_right.set_ylabel('') # 우측 그래프는 Y축 라벨 중복 제거

    ax_left.set_xlabel('Mean Importance Score', fontsize=10)
    ax_right.set_xlabel('Mean Importance Score', fontsize=10)

# 간격 최적화 후 도표 띄우기
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
import warnings

warnings.filterwarnings('ignore')


sns.set_theme(style="whitegrid")
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['axes.unicode_minus'] = False


# 2. 데이터 로드 및 K-Means 클러스터링

df = pd.read_csv("hotel_bookings_preprocessed.csv")

cluster_cols = ['adr', 'stays_in_weekend_nights', 'stays_in_week_nights', 'total_of_special_requests']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[cluster_cols])

kmeans = KMeans(n_clusters=3, random_state=42)
df['customer_cluster'] = kmeans.fit_predict(X_scaled)


# 3. 3개 군집 x 3개 모델 = 3행 3열 대형 서브플롯 틀 생성

fig, axes = plt.subplots(3, 3, figsize=(18, 14))
fig.suptitle('5-Fold CV Feature Importance: Boosting Trilogy (AdaBoost vs GBM vs XGBoost)', fontsize=22, fontweight='bold', y=0.98)

cluster_names = {
    0: "Cluster 0: Budget Personal",
    1: "Cluster 1: Long-stay Family/Groups",
    2: "Cluster 2: High-spending VIPs"
}

folds = 5
skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=42)


# 4. 5-Fold 교차 검증 기반 부스팅 피처 중요도 추출 및 시각화

for row_idx, cluster_id in enumerate(sorted(df['customer_cluster'].unique())):
    df_cluster = df[df['customer_cluster'] == cluster_id]

    X_c = df_cluster.drop(columns=['is_canceled', 'customer_cluster']).reset_index(drop=True)
    y_c = df_cluster['is_canceled'].reset_index(drop=True)
    features = X_c.columns

    # 각 폴드의 중요도를 모을 빈 리스트
    ada_folds_imp = []
    gbm_folds_imp = []
    xgb_folds_imp = []

    for train_idx, _ in skf.split(X_c, y_c):
        X_train, y_train = X_c.iloc[train_idx], y_c.iloc[train_idx]

        # 수업 PDF 규격 준수 하이퍼파라미터 모델 정의 (Ref: Slide Page 72, 113, 117)
        m_ada = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1, random_state=42), n_estimators=100, random_state=42)
        m_gbm = GradientBoostingClassifier(n_estimators=100, max_depth=3, random_state=42)
        m_xgb = XGBClassifier(n_estimators=100, max_depth=3, random_state=42, eval_metric='logloss')

        m_ada.fit(X_train, y_train)
        m_gbm.fit(X_train, y_train)
        m_xgb.fit(X_train, y_train)

        ada_folds_imp.append(m_ada.feature_importances_)
        gbm_folds_imp.append(m_gbm.feature_importances_)
        xgb_folds_imp.append(m_xgb.feature_importances_)

    # 5개 폴드 결과의 산술 평균 계산
    ada_final_avg = np.mean(ada_folds_imp, axis=0)
    gbm_final_avg = np.mean(gbm_folds_imp, axis=0)
    xgb_final_avg = np.mean(xgb_folds_imp, axis=0)

    model_data_mappings = [
        ('AdaBoost (Stumps)', ada_final_avg, "Purples_r"),
        ('Gradient Boosting', gbm_final_avg, "Greens_r"),
        ('XGBoost (Regularized)', xgb_final_avg, "Reds_r")
    ]

    # 3개 열에 순서대로 데이터 바인딩 및 시본 그래프 작도
    for col_idx, (model_name, importance, color_palette) in enumerate(model_data_mappings):
        ax = axes[row_idx, col_idx]

        fi_df = pd.DataFrame({'Feature': features, 'Importance': importance}).sort_values(by='Importance', ascending=False).head(5)

        sns.barplot(x='Importance', y='Feature', data=fi_df, ax=ax, palette=color_palette)

        # 첫 번째 행에만 상단 모델 타이틀 부여
        if row_idx == 0:
            ax.set_title(f' {model_name}', fontsize=14, fontweight='bold', pad=10)

        # 첫 번째 열에만 좌측 군집 세그먼트 성향 라벨 매핑
        if col_idx == 0:
            ax.set_ylabel(f"{cluster_names[cluster_id]}", fontsize=12, fontweight='bold', labelpad=15)
        else:
            ax.set_ylabel('')

        ax.set_xlabel('Mean Importance Score', fontsize=10)

# 레이아웃 정돈 후 플롯 출력
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()